SELECT * FROM pokedex.pokemon;
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (001, "./image/Bulbasaur.png","Bulbasaur","Bulbasaur es un Pokémon de tipo planta/veneno introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Squirtle y Charmander (excepto en Pokémon Amarillo)",50,50);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (002,"./image/Ivysaur.png","Ivysaur","Ivysaur es un Pokémon de tipo planta/veneno introducido en la primera generación. Es la evolución de Bulbasaur, uno de los Pokémon iniciales de Kanto.",130,10,1);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (003,"./image/Venusaur.png","Venusaur","Venusaur es un Pokémon de tipo planta/veneno introducido en la primera generación. Es la evolución de Ivysaur y, a partir de la sexta generación, puede megaevolucionar en Mega-Venusaur.",1000,20,2);

#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (004,"./image/Charmander.webp","Charmander","Charmander es un Pokémon de tipo fuego introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Bulbasaur y Squirtle",85,6);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (005,"./image/Charmeleon.webp","Charmeleon","Charmeleon es un Pokémon de tipo fuego introducido en la primera generación. Es la evolución de Charmander, uno de los Pokémon iniciales de los entrenadores que comienzan su aventura en la región de Kanto.",190,11,4);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (006,"./image/Charizard.webp","Charizard","Charizard es un Pokémon de tipo fuego/volador, introducido en la primera generación. Es la evolución de Charmeleon y, a partir de la sexta generación, puede megaevolucionar en Mega-Charizard X o en Mega-Charizard Y.",905,17,5);007,"./image/Squirtle.webp",Squirtle,"Squirtle es un Pokémon de tipo agua introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Bulbasaur y Charmander, excepto en Pokémon Amarillo.",90,5

#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (007,"./image/Squirtle.webp","Squirtle","Squirtle es un Pokémon de tipo agua introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Bulbasaur y Charmander, excepto en Pokémon Amarillo.",90,5);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (008,"./image/Wartortle.webp","Wartortle","Wartortle es un Pokémon de tipo agua introducido en la primera generación. Es la forma evolucionada de Squirtle, uno de los Pokémon iniciales de Kanto.",225,10,7);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (009,"./image/Blastoise.webp","Blastoise","Blastoise es un Pokémon de tipo agua introducido en la primera generación. Es la evolución de Wartortle y, a partir de la sexta generación, puede megaevolucionar en Mega-Blastoise.",855,16,8);

#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (010,"./image/Caterpie.webp","Caterpie","Caterpie es un Pokémon de tipo bicho introducido en la primera generación. Es la contraparte de Weedle.",39,3);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (011,"./image/Metapod.webp","Metapod","Metapod es un Pokémon de tipo bicho introducido en la primera generación. Es la evolución de Caterpie. Es la contraparte de Kakuna..",99,7,10);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (012,"./image/Butterfree.webp","Butterfree","Butterfree es un Pokémon tipo bicho/volador introducido en la primera generación. Es la evolución de Metapod. Es la contraparte de Beedrill.",320,11,11);

#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (013,"./image/Weedle.webp","Weedle","Weedle es un Pokémon del tipo bicho/veneno introducido en la primera generación. Es la contraparte de Caterpie.",32,3);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (014,"./image/Kakuna.webp","Kakuna","Kakuna es un Pokémon tipo bicho/veneno introducido en la primera generación. Es la evolución de Weedle. Es la contraparte de Metapod.",100,6,13);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (015,"./image/Beedrill.webp","Beedrill","Beedrill es un Pokémon de tipo bicho/veneno introducido en la primera generación. Es la evolución de Kakuna. A partir de Pokémon Rubí Omega y Pokémon Zafiro Alfa puede megaevolucionar en Mega-Beedrill. Es la contraparte de Butterfree.",295,10,14);

#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (016,"./image/Pidgey.webp","Pidgey","Pidgey es un Pokémon de tipo normal/volador introducido en la primera generación.",18,3);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (017,"./image/Pidgeotto.webp","Pidgeotto","Pidgeotto es un Pokémon introducido en la primera generación. Es de tipo normal/volador. Es la forma evolucionada de Pidgey.",300,11,16);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (018,"./image/Pidgeot.webp","Pidgeot","Pidgeot es un Pokémon del tipo normal/volador introducido en la primera generación. Es la forma evolucionada de Pidgeotto. A partir de Pokémon Rubí Omega y Pokémon Zafiro Alfa puede megaevolucionar en Mega-Pidgeot.",395,15,17);

