SELECT * FROM pokedex.pokemon;
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (001, "./image/Bulbasaur.png","Bulbasaur","Bulbasaur es un Pokémon de tipo planta/veneno introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Squirtle y Charmander (excepto en Pokémon Amarillo)",50,50);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (002,"./image/Ivysaur.png","Ivysaur","Ivysaur es un Pokémon de tipo planta/veneno introducido en la primera generación. Es la evolución de Bulbasaur, uno de los Pokémon iniciales de Kanto.",130,10,1);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (003,"./image/Venusaur.png","Venusaur","Venusaur es un Pokémon de tipo planta/veneno introducido en la primera generación. Es la evolución de Ivysaur y, a partir de la sexta generación, puede megaevolucionar en Mega-Venusaur.",1000,20,2);

#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (004,"./image/Charmander.webp","Charmander","Charmander es un Pokémon de tipo fuego introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Bulbasaur y Squirtle",85,6);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (005,"./image/Charmeleon.webp","Charmeleon","Charmeleon es un Pokémon de tipo fuego introducido en la primera generación. Es la evolución de Charmander, uno de los Pokémon iniciales de los entrenadores que comienzan su aventura en la región de Kanto.",190,11,4);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (006,"./image/Charizard.webp","Charizard","Charizard es un Pokémon de tipo fuego/volador, introducido en la primera generación. Es la evolución de Charmeleon y, a partir de la sexta generación, puede megaevolucionar en Mega-Charizard X o en Mega-Charizard Y.",905,17,5);007,"./image/Squirtle.webp",Squirtle,"Squirtle es un Pokémon de tipo agua introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Bulbasaur y Charmander, excepto en Pokémon Amarillo.",90,5

#INSERT INTO pokemon (order_number, image_path,name,description,weight,height) VALUES (007,"./image/Squirtle.webp","Squirtle","Squirtle es un Pokémon de tipo agua introducido en la primera generación. Es uno de los Pokémon iniciales que pueden elegir los entrenadores que empiezan su aventura en la región Kanto, junto a Bulbasaur y Charmander, excepto en Pokémon Amarillo.",90,5);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (008,"./image/Wartortle.webp","Wartortle","Wartortle es un Pokémon de tipo agua introducido en la primera generación. Es la forma evolucionada de Squirtle, uno de los Pokémon iniciales de Kanto.",225,10,7);
#INSERT INTO pokemon (order_number, image_path,name,description,weight,height,parent_id) VALUES (009,"./image/Blastoise.webp","Blastoise","Blastoise es un Pokémon de tipo agua introducido en la primera generación. Es la evolución de Wartortle y, a partir de la sexta generación, puede megaevolucionar en Mega-Blastoise.",855,16,8);

